# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.models.pipeline_state_in_progress_paused_all_of import PipelineStateInProgressPausedAllOf  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestPipelineStateInProgressPausedAllOf(unittest.TestCase):
    """PipelineStateInProgressPausedAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPipelineStateInProgressPausedAllOf(self):
        """Test PipelineStateInProgressPausedAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bitbucketopenapi.models.pipeline_state_in_progress_paused_all_of.PipelineStateInProgressPausedAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
