# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.snippet_api import SnippetApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestSnippetApi(unittest.TestCase):
    """SnippetApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.snippet_api.SnippetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_snippets_by_username_by_encoded_id_files_by_path(self):
        """Test case for get_snippets_by_username_by_encoded_id_files_by_path

        """
        pass


if __name__ == '__main__':
    unittest.main()
