# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.users_api import UsersApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_users_by_username_hooks(self):
        """Test case for create_users_by_username_hooks

        """
        pass

    def test_delete_users_by_username_hooks_by_uid(self):
        """Test case for delete_users_by_username_hooks_by_uid

        """
        pass

    def test_get_teams_by_username_repositories(self):
        """Test case for get_teams_by_username_repositories

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_get_user_emails(self):
        """Test case for get_user_emails

        """
        pass

    def test_get_user_emails_by_email(self):
        """Test case for get_user_emails_by_email

        """
        pass

    def test_get_users_by_username(self):
        """Test case for get_users_by_username

        """
        pass

    def test_get_users_by_username_followers(self):
        """Test case for get_users_by_username_followers

        """
        pass

    def test_get_users_by_username_following(self):
        """Test case for get_users_by_username_following

        """
        pass

    def test_get_users_by_username_hooks(self):
        """Test case for get_users_by_username_hooks

        """
        pass

    def test_get_users_by_username_hooks_by_uid(self):
        """Test case for get_users_by_username_hooks_by_uid

        """
        pass

    def test_get_users_by_username_repositories(self):
        """Test case for get_users_by_username_repositories

        """
        pass

    def test_update_users_by_username_hooks_by_uid(self):
        """Test case for update_users_by_username_hooks_by_uid

        """
        pass


if __name__ == '__main__':
    unittest.main()
