# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.branching_model_api import BranchingModelApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestBranchingModelApi(unittest.TestCase):
    """BranchingModelApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.branching_model_api.BranchingModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_repositories_by_username_by_repo_slug_branchingmodel(self):
        """Test case for get_repositories_by_username_by_repo_slug_branchingmodel

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_branchingmodel_settings(self):
        """Test case for get_repositories_by_username_by_repo_slug_branchingmodel_settings

        """
        pass

    def test_update_repositories_by_username_by_repo_slug_branchingmodel_settings(self):
        """Test case for update_repositories_by_username_by_repo_slug_branchingmodel_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
