# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.search_api import SearchApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_account(self):
        """Test case for search_account

        Search for code in the repositories of the specified team  # noqa: E501
        """
        pass

    def test_search_account_0(self):
        """Test case for search_account_0

        Search for code in the repositories of the specified user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
