# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.snippets_api import SnippetsApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestSnippetsApi(unittest.TestCase):
    """SnippetsApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.snippets_api.SnippetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_snippets(self):
        """Test case for create_snippets

        """
        pass

    def test_create_snippets_by_username(self):
        """Test case for create_snippets_by_username

        """
        pass

    def test_create_snippets_by_username_by_encoded_id_comments(self):
        """Test case for create_snippets_by_username_by_encoded_id_comments

        """
        pass

    def test_delete_snippets_by_username_by_encoded_id(self):
        """Test case for delete_snippets_by_username_by_encoded_id

        """
        pass

    def test_delete_snippets_by_username_by_encoded_id_by_node_id(self):
        """Test case for delete_snippets_by_username_by_encoded_id_by_node_id

        """
        pass

    def test_delete_snippets_by_username_by_encoded_id_comments_by_comment_id(self):
        """Test case for delete_snippets_by_username_by_encoded_id_comments_by_comment_id

        """
        pass

    def test_delete_snippets_by_username_by_encoded_id_watch(self):
        """Test case for delete_snippets_by_username_by_encoded_id_watch

        """
        pass

    def test_get_snippets(self):
        """Test case for get_snippets

        """
        pass

    def test_get_snippets_by_username(self):
        """Test case for get_snippets_by_username

        """
        pass

    def test_get_snippets_by_username_by_encoded_id(self):
        """Test case for get_snippets_by_username_by_encoded_id

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_by_node_id(self):
        """Test case for get_snippets_by_username_by_encoded_id_by_node_id

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_by_node_id_files_by_path(self):
        """Test case for get_snippets_by_username_by_encoded_id_by_node_id_files_by_path

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_by_revision_diff(self):
        """Test case for get_snippets_by_username_by_encoded_id_by_revision_diff

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_by_revision_patch(self):
        """Test case for get_snippets_by_username_by_encoded_id_by_revision_patch

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_comments(self):
        """Test case for get_snippets_by_username_by_encoded_id_comments

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_comments_by_comment_id(self):
        """Test case for get_snippets_by_username_by_encoded_id_comments_by_comment_id

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_commits(self):
        """Test case for get_snippets_by_username_by_encoded_id_commits

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_commits_by_revision(self):
        """Test case for get_snippets_by_username_by_encoded_id_commits_by_revision

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_watch(self):
        """Test case for get_snippets_by_username_by_encoded_id_watch

        """
        pass

    def test_get_snippets_by_username_by_encoded_id_watchers(self):
        """Test case for get_snippets_by_username_by_encoded_id_watchers

        """
        pass

    def test_update_snippets_by_username_by_encoded_id(self):
        """Test case for update_snippets_by_username_by_encoded_id

        """
        pass

    def test_update_snippets_by_username_by_encoded_id_by_node_id(self):
        """Test case for update_snippets_by_username_by_encoded_id_by_node_id

        """
        pass

    def test_update_snippets_by_username_by_encoded_id_comments_by_comment_id(self):
        """Test case for update_snippets_by_username_by_encoded_id_comments_by_comment_id

        """
        pass

    def test_update_snippets_by_username_by_encoded_id_watch(self):
        """Test case for update_snippets_by_username_by_encoded_id_watch

        """
        pass


if __name__ == '__main__':
    unittest.main()
