# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.downloads_api import DownloadsApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestDownloadsApi(unittest.TestCase):
    """DownloadsApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.downloads_api.DownloadsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_by_username_by_repo_slug_downloads(self):
        """Test case for create_repositories_by_username_by_repo_slug_downloads

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_downloads_by_filename(self):
        """Test case for delete_repositories_by_username_by_repo_slug_downloads_by_filename

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_downloads(self):
        """Test case for get_repositories_by_username_by_repo_slug_downloads

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_downloads_by_filename(self):
        """Test case for get_repositories_by_username_by_repo_slug_downloads_by_filename

        """
        pass


if __name__ == '__main__':
    unittest.main()
