# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.pullrequests_api import PullrequestsApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestPullrequestsApi(unittest.TestCase):
    """PullrequestsApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.pullrequests_api.PullrequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_by_username_by_repo_slug_pullrequests(self):
        """Test case for create_repositories_by_username_by_repo_slug_pullrequests

        """
        pass

    def test_create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_approve(self):
        """Test case for create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_approve

        """
        pass

    def test_create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments(self):
        """Test case for create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments

        """
        pass

    def test_create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_decline(self):
        """Test case for create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_decline

        """
        pass

    def test_create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_merge(self):
        """Test case for create_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_merge

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_defaultreviewers_by_target_username(self):
        """Test case for delete_repositories_by_username_by_repo_slug_defaultreviewers_by_target_username

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_approve(self):
        """Test case for delete_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_approve

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments_by_comment_id(self):
        """Test case for delete_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments_by_comment_id

        """
        pass

    def test_get_pullrequests_by_target_user(self):
        """Test case for get_pullrequests_by_target_user

        """
        pass

    def test_get_pullrequests_for_commit(self):
        """Test case for get_pullrequests_for_commit

        Returns a paginated list of all pull requests as part of which this commit was reviewed.  # noqa: E501
        """
        pass

    def test_get_repositories_by_username_by_repo_slug_defaultreviewers(self):
        """Test case for get_repositories_by_username_by_repo_slug_defaultreviewers

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_defaultreviewers_by_target_username(self):
        """Test case for get_repositories_by_username_by_repo_slug_defaultreviewers_by_target_username

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_activity(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_activity

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_activity(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_activity

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments_by_comment_id(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments_by_comment_id

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_commits(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_commits

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_diff(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_diff

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_diffstat(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_diffstat

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_patch(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_patch

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_statuses(self):
        """Test case for get_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_statuses

        """
        pass

    def test_update_repositories_by_username_by_repo_slug_defaultreviewers_by_target_username(self):
        """Test case for update_repositories_by_username_by_repo_slug_defaultreviewers_by_target_username

        """
        pass

    def test_update_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id(self):
        """Test case for update_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id

        """
        pass

    def test_update_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments_by_comment_id(self):
        """Test case for update_repositories_by_username_by_repo_slug_pullrequests_by_pull_request_id_comments_by_comment_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
