# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.ssh_api import SshApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestSshApi(unittest.TestCase):
    """SshApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.ssh_api.SshApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_users_by_username_sshkeys(self):
        """Test case for create_users_by_username_sshkeys

        """
        pass

    def test_delete_users_by_username_sshkeys(self):
        """Test case for delete_users_by_username_sshkeys

        """
        pass

    def test_get_users_by_username_sshkeys(self):
        """Test case for get_users_by_username_sshkeys

        """
        pass

    def test_get_users_by_username_sshkeys_0(self):
        """Test case for get_users_by_username_sshkeys_0

        """
        pass

    def test_update_users_by_username_sshkeys(self):
        """Test case for update_users_by_username_sshkeys

        """
        pass


if __name__ == '__main__':
    unittest.main()
