# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.refs_api import RefsApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestRefsApi(unittest.TestCase):
    """RefsApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.refs_api.RefsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_by_username_by_repo_slug_refs_branches(self):
        """Test case for create_repositories_by_username_by_repo_slug_refs_branches

        """
        pass

    def test_create_repositories_by_username_by_repo_slug_refs_tags(self):
        """Test case for create_repositories_by_username_by_repo_slug_refs_tags

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_refs_branches_by_name(self):
        """Test case for delete_repositories_by_username_by_repo_slug_refs_branches_by_name

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_refs_tags_by_name(self):
        """Test case for delete_repositories_by_username_by_repo_slug_refs_tags_by_name

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_refs(self):
        """Test case for get_repositories_by_username_by_repo_slug_refs

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_refs_branches(self):
        """Test case for get_repositories_by_username_by_repo_slug_refs_branches

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_refs_branches_by_name(self):
        """Test case for get_repositories_by_username_by_repo_slug_refs_branches_by_name

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_refs_tags(self):
        """Test case for get_repositories_by_username_by_repo_slug_refs_tags

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_refs_tags_by_name(self):
        """Test case for get_repositories_by_username_by_repo_slug_refs_tags_by_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
