# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.pipelines_api import PipelinesApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestPipelinesApi(unittest.TestCase):
    """PipelinesApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.pipelines_api.PipelinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_pipeline_for_repository(self):
        """Test case for create_pipeline_for_repository

        """
        pass

    def test_create_pipeline_variable_for_team(self):
        """Test case for create_pipeline_variable_for_team

        """
        pass

    def test_create_pipeline_variable_for_user(self):
        """Test case for create_pipeline_variable_for_user

        """
        pass

    def test_create_repository_pipeline_known_host(self):
        """Test case for create_repository_pipeline_known_host

        """
        pass

    def test_create_repository_pipeline_schedule(self):
        """Test case for create_repository_pipeline_schedule

        """
        pass

    def test_create_repository_pipeline_variable(self):
        """Test case for create_repository_pipeline_variable

        """
        pass

    def test_delete_pipeline_variable_for_team(self):
        """Test case for delete_pipeline_variable_for_team

        """
        pass

    def test_delete_pipeline_variable_for_user(self):
        """Test case for delete_pipeline_variable_for_user

        """
        pass

    def test_delete_repository_pipeline_key_pair(self):
        """Test case for delete_repository_pipeline_key_pair

        """
        pass

    def test_delete_repository_pipeline_known_host(self):
        """Test case for delete_repository_pipeline_known_host

        """
        pass

    def test_delete_repository_pipeline_schedule(self):
        """Test case for delete_repository_pipeline_schedule

        """
        pass

    def test_delete_repository_pipeline_variable(self):
        """Test case for delete_repository_pipeline_variable

        """
        pass

    def test_get_pipeline_for_repository(self):
        """Test case for get_pipeline_for_repository

        """
        pass

    def test_get_pipeline_step_for_repository(self):
        """Test case for get_pipeline_step_for_repository

        """
        pass

    def test_get_pipeline_step_log_for_repository(self):
        """Test case for get_pipeline_step_log_for_repository

        """
        pass

    def test_get_pipeline_steps_for_repository(self):
        """Test case for get_pipeline_steps_for_repository

        """
        pass

    def test_get_pipeline_variable_for_team(self):
        """Test case for get_pipeline_variable_for_team

        """
        pass

    def test_get_pipeline_variable_for_user(self):
        """Test case for get_pipeline_variable_for_user

        """
        pass

    def test_get_pipeline_variables_for_team(self):
        """Test case for get_pipeline_variables_for_team

        """
        pass

    def test_get_pipeline_variables_for_user(self):
        """Test case for get_pipeline_variables_for_user

        """
        pass

    def test_get_pipelines_for_repository(self):
        """Test case for get_pipelines_for_repository

        """
        pass

    def test_get_repository_pipeline_config(self):
        """Test case for get_repository_pipeline_config

        """
        pass

    def test_get_repository_pipeline_known_host(self):
        """Test case for get_repository_pipeline_known_host

        """
        pass

    def test_get_repository_pipeline_known_hosts(self):
        """Test case for get_repository_pipeline_known_hosts

        """
        pass

    def test_get_repository_pipeline_schedule(self):
        """Test case for get_repository_pipeline_schedule

        """
        pass

    def test_get_repository_pipeline_schedule_executions(self):
        """Test case for get_repository_pipeline_schedule_executions

        """
        pass

    def test_get_repository_pipeline_schedules(self):
        """Test case for get_repository_pipeline_schedules

        """
        pass

    def test_get_repository_pipeline_ssh_key_pair(self):
        """Test case for get_repository_pipeline_ssh_key_pair

        """
        pass

    def test_get_repository_pipeline_variable(self):
        """Test case for get_repository_pipeline_variable

        """
        pass

    def test_get_repository_pipeline_variables(self):
        """Test case for get_repository_pipeline_variables

        """
        pass

    def test_stop_pipeline(self):
        """Test case for stop_pipeline

        """
        pass

    def test_update_pipeline_variable_for_team(self):
        """Test case for update_pipeline_variable_for_team

        """
        pass

    def test_update_pipeline_variable_for_user(self):
        """Test case for update_pipeline_variable_for_user

        """
        pass

    def test_update_repository_build_number(self):
        """Test case for update_repository_build_number

        """
        pass

    def test_update_repository_pipeline_config(self):
        """Test case for update_repository_pipeline_config

        """
        pass

    def test_update_repository_pipeline_key_pair(self):
        """Test case for update_repository_pipeline_key_pair

        """
        pass

    def test_update_repository_pipeline_known_host(self):
        """Test case for update_repository_pipeline_known_host

        """
        pass

    def test_update_repository_pipeline_schedule(self):
        """Test case for update_repository_pipeline_schedule

        """
        pass

    def test_update_repository_pipeline_variable(self):
        """Test case for update_repository_pipeline_variable

        """
        pass


if __name__ == '__main__':
    unittest.main()
