# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.teams_api import TeamsApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_teams_by_username_hooks(self):
        """Test case for create_teams_by_username_hooks

        """
        pass

    def test_delete_teams_by_username_hooks_by_uid(self):
        """Test case for delete_teams_by_username_hooks_by_uid

        """
        pass

    def test_get_teams(self):
        """Test case for get_teams

        """
        pass

    def test_get_teams_by_username(self):
        """Test case for get_teams_by_username

        """
        pass

    def test_get_teams_by_username_followers(self):
        """Test case for get_teams_by_username_followers

        """
        pass

    def test_get_teams_by_username_following(self):
        """Test case for get_teams_by_username_following

        """
        pass

    def test_get_teams_by_username_hooks(self):
        """Test case for get_teams_by_username_hooks

        """
        pass

    def test_get_teams_by_username_hooks_by_uid(self):
        """Test case for get_teams_by_username_hooks_by_uid

        """
        pass

    def test_get_teams_by_username_members(self):
        """Test case for get_teams_by_username_members

        """
        pass

    def test_get_teams_by_username_repositories(self):
        """Test case for get_teams_by_username_repositories

        """
        pass

    def test_get_users_by_username_members(self):
        """Test case for get_users_by_username_members

        """
        pass

    def test_get_users_by_username_repositories(self):
        """Test case for get_users_by_username_repositories

        """
        pass

    def test_update_teams_by_username_hooks_by_uid(self):
        """Test case for update_teams_by_username_hooks_by_uid

        """
        pass


if __name__ == '__main__':
    unittest.main()
