# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.branchrestrictions_api import BranchrestrictionsApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestBranchrestrictionsApi(unittest.TestCase):
    """BranchrestrictionsApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.branchrestrictions_api.BranchrestrictionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_by_username_by_repo_slug_branchrestrictions(self):
        """Test case for create_repositories_by_username_by_repo_slug_branchrestrictions

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_branchrestrictions_by_id(self):
        """Test case for delete_repositories_by_username_by_repo_slug_branchrestrictions_by_id

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_branchrestrictions(self):
        """Test case for get_repositories_by_username_by_repo_slug_branchrestrictions

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_branchrestrictions_by_id(self):
        """Test case for get_repositories_by_username_by_repo_slug_branchrestrictions_by_id

        """
        pass

    def test_update_repositories_by_username_by_repo_slug_branchrestrictions_by_id(self):
        """Test case for update_repositories_by_username_by_repo_slug_branchrestrictions_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
