# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.default_api import DefaultApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_by_username_by_repo_slug_issues_export(self):
        """Test case for create_repositories_by_username_by_repo_slug_issues_export

        """
        pass

    def test_create_repositories_by_username_by_repo_slug_issues_import(self):
        """Test case for create_repositories_by_username_by_repo_slug_issues_import

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_diffstat_by_spec(self):
        """Test case for get_repositories_by_username_by_repo_slug_diffstat_by_spec

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_issues_export_by_repo_nameissuesby_task_id_zip(self):
        """Test case for get_repositories_by_username_by_repo_slug_issues_export_by_repo_nameissuesby_task_id_zip

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_issues_import(self):
        """Test case for get_repositories_by_username_by_repo_slug_issues_import

        """
        pass

    def test_get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_logs_by_log_uuid(self):
        """Test case for get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_logs_by_log_uuid

        """
        pass

    def test_get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_test_reports(self):
        """Test case for get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_test_reports

        """
        pass

    def test_get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_test_reports_test_cases(self):
        """Test case for get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_test_reports_test_cases

        """
        pass

    def test_get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_test_reports_test_cases_by_test_case_uuid_test_case_reasons(self):
        """Test case for get_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_steps_by_step_uuid_test_reports_test_cases_by_test_case_uuid_test_case_reasons

        """
        pass

    def test_get_teams_by_username_permissions(self):
        """Test case for get_teams_by_username_permissions

        """
        pass

    def test_get_teams_by_username_permissions_repositories(self):
        """Test case for get_teams_by_username_permissions_repositories

        """
        pass

    def test_get_teams_by_username_permissions_repositories_by_repo_slug(self):
        """Test case for get_teams_by_username_permissions_repositories_by_repo_slug

        """
        pass

    def test_get_user_permissions_teams(self):
        """Test case for get_user_permissions_teams

        """
        pass

    def test_update_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_remotetriggers_by_trigger_key(self):
        """Test case for update_repositories_by_workspace_by_repo_slug_pipelines_by_pipeline_uuid_remotetriggers_by_trigger_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
