# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bitbucketopenapi
from bitbucketopenapi.api.webhooks_api import WebhooksApi  # noqa: E501
from bitbucketopenapi.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = bitbucketopenapi.api.webhooks_api.WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_by_username_by_repo_slug_hooks(self):
        """Test case for create_repositories_by_username_by_repo_slug_hooks

        """
        pass

    def test_create_teams_by_username_hooks(self):
        """Test case for create_teams_by_username_hooks

        """
        pass

    def test_create_users_by_username_hooks(self):
        """Test case for create_users_by_username_hooks

        """
        pass

    def test_delete_repositories_by_username_by_repo_slug_hooks_by_uid(self):
        """Test case for delete_repositories_by_username_by_repo_slug_hooks_by_uid

        """
        pass

    def test_delete_teams_by_username_hooks_by_uid(self):
        """Test case for delete_teams_by_username_hooks_by_uid

        """
        pass

    def test_delete_users_by_username_hooks_by_uid(self):
        """Test case for delete_users_by_username_hooks_by_uid

        """
        pass

    def test_get_hook_events(self):
        """Test case for get_hook_events

        """
        pass

    def test_get_hook_events_by_subject_type(self):
        """Test case for get_hook_events_by_subject_type

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_hooks(self):
        """Test case for get_repositories_by_username_by_repo_slug_hooks

        """
        pass

    def test_get_repositories_by_username_by_repo_slug_hooks_by_uid(self):
        """Test case for get_repositories_by_username_by_repo_slug_hooks_by_uid

        """
        pass

    def test_get_teams_by_username_hooks(self):
        """Test case for get_teams_by_username_hooks

        """
        pass

    def test_get_teams_by_username_hooks_by_uid(self):
        """Test case for get_teams_by_username_hooks_by_uid

        """
        pass

    def test_get_users_by_username_hooks(self):
        """Test case for get_users_by_username_hooks

        """
        pass

    def test_get_users_by_username_hooks_by_uid(self):
        """Test case for get_users_by_username_hooks_by_uid

        """
        pass

    def test_update_repositories_by_username_by_repo_slug_hooks_by_uid(self):
        """Test case for update_repositories_by_username_by_repo_slug_hooks_by_uid

        """
        pass

    def test_update_teams_by_username_hooks_by_uid(self):
        """Test case for update_teams_by_username_hooks_by_uid

        """
        pass

    def test_update_users_by_username_hooks_by_uid(self):
        """Test case for update_users_by_username_hooks_by_uid

        """
        pass


if __name__ == '__main__':
    unittest.main()
