# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CommitstatusAllOfLinks(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'commit': 'AccountAllOfLinksAvatar',
        '_self': 'AccountAllOfLinksAvatar'
    }

    attribute_map = {
        'commit': 'commit',
        '_self': 'self'
    }

    def __init__(self, commit=None, _self=None):  # noqa: E501
        """CommitstatusAllOfLinks - a model defined in OpenAPI"""  # noqa: E501

        self._commit = None
        self.__self = None
        self.discriminator = None

        if commit is not None:
            self.commit = commit
        if _self is not None:
            self._self = _self

    @property
    def commit(self):
        """Gets the commit of this CommitstatusAllOfLinks.  # noqa: E501


        :return: The commit of this CommitstatusAllOfLinks.  # noqa: E501
        :rtype: AccountAllOfLinksAvatar
        """
        return self._commit

    @commit.setter
    def commit(self, commit):
        """Sets the commit of this CommitstatusAllOfLinks.


        :param commit: The commit of this CommitstatusAllOfLinks.  # noqa: E501
        :type: AccountAllOfLinksAvatar
        """

        self._commit = commit

    @property
    def _self(self):
        """Gets the _self of this CommitstatusAllOfLinks.  # noqa: E501


        :return: The _self of this CommitstatusAllOfLinks.  # noqa: E501
        :rtype: AccountAllOfLinksAvatar
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this CommitstatusAllOfLinks.


        :param _self: The _self of this CommitstatusAllOfLinks.  # noqa: E501
        :type: AccountAllOfLinksAvatar
        """

        self.__self = _self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommitstatusAllOfLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
