# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DeploymentStateUndeployed(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'trigger_url': 'str'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'trigger_url': 'trigger_url'
    }

    def __init__(self, type=None, name=None, trigger_url=None):  # noqa: E501
        """DeploymentStateUndeployed - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._name = None
        self._trigger_url = None
        self.discriminator = None

        self.type = type
        if name is not None:
            self.name = name
        if trigger_url is not None:
            self.trigger_url = trigger_url

    @property
    def type(self):
        """Gets the type of this DeploymentStateUndeployed.  # noqa: E501


        :return: The type of this DeploymentStateUndeployed.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DeploymentStateUndeployed.


        :param type: The type of this DeploymentStateUndeployed.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this DeploymentStateUndeployed.  # noqa: E501

        The name of deployment state (UNDEPLOYED).  # noqa: E501

        :return: The name of this DeploymentStateUndeployed.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeploymentStateUndeployed.

        The name of deployment state (UNDEPLOYED).  # noqa: E501

        :param name: The name of this DeploymentStateUndeployed.  # noqa: E501
        :type: str
        """
        allowed_values = ["UNDEPLOYED"]  # noqa: E501
        if name not in allowed_values:
            raise ValueError(
                "Invalid value for `name` ({0}), must be one of {1}"  # noqa: E501
                .format(name, allowed_values)
            )

        self._name = name

    @property
    def trigger_url(self):
        """Gets the trigger_url of this DeploymentStateUndeployed.  # noqa: E501

        Link to trigger the deployment.  # noqa: E501

        :return: The trigger_url of this DeploymentStateUndeployed.  # noqa: E501
        :rtype: str
        """
        return self._trigger_url

    @trigger_url.setter
    def trigger_url(self, trigger_url):
        """Sets the trigger_url of this DeploymentStateUndeployed.

        Link to trigger the deployment.  # noqa: E501

        :param trigger_url: The trigger_url of this DeploymentStateUndeployed.  # noqa: E501
        :type: str
        """

        self._trigger_url = trigger_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeploymentStateUndeployed):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
