# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ErrorError(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data': 'object',
        'detail': 'str',
        'message': 'str'
    }

    attribute_map = {
        'data': 'data',
        'detail': 'detail',
        'message': 'message'
    }

    def __init__(self, data=None, detail=None, message=None):  # noqa: E501
        """ErrorError - a model defined in OpenAPI"""  # noqa: E501

        self._data = None
        self._detail = None
        self._message = None
        self.discriminator = None

        if data is not None:
            self.data = data
        if detail is not None:
            self.detail = detail
        self.message = message

    @property
    def data(self):
        """Gets the data of this ErrorError.  # noqa: E501

        Optional structured data that is endpoint-specific.  # noqa: E501

        :return: The data of this ErrorError.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ErrorError.

        Optional structured data that is endpoint-specific.  # noqa: E501

        :param data: The data of this ErrorError.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def detail(self):
        """Gets the detail of this ErrorError.  # noqa: E501


        :return: The detail of this ErrorError.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this ErrorError.


        :param detail: The detail of this ErrorError.  # noqa: E501
        :type: str
        """

        self._detail = detail

    @property
    def message(self):
        """Gets the message of this ErrorError.  # noqa: E501


        :return: The message of this ErrorError.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorError.


        :param message: The message of this ErrorError.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
