# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class IssueChangeChanges(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'assignee': 'IssueChangeChangesAssignee',
        'component': 'IssueChangeChangesAssignee',
        'content': 'IssueChangeChangesAssignee',
        'kind': 'IssueChangeChangesAssignee',
        'milestone': 'IssueChangeChangesAssignee',
        'priority': 'IssueChangeChangesAssignee',
        'state': 'IssueChangeChangesAssignee',
        'title': 'IssueChangeChangesAssignee',
        'version': 'IssueChangeChangesAssignee'
    }

    attribute_map = {
        'assignee': 'assignee',
        'component': 'component',
        'content': 'content',
        'kind': 'kind',
        'milestone': 'milestone',
        'priority': 'priority',
        'state': 'state',
        'title': 'title',
        'version': 'version'
    }

    def __init__(self, assignee=None, component=None, content=None, kind=None, milestone=None, priority=None, state=None, title=None, version=None):  # noqa: E501
        """IssueChangeChanges - a model defined in OpenAPI"""  # noqa: E501

        self._assignee = None
        self._component = None
        self._content = None
        self._kind = None
        self._milestone = None
        self._priority = None
        self._state = None
        self._title = None
        self._version = None
        self.discriminator = None

        if assignee is not None:
            self.assignee = assignee
        if component is not None:
            self.component = component
        if content is not None:
            self.content = content
        if kind is not None:
            self.kind = kind
        if milestone is not None:
            self.milestone = milestone
        if priority is not None:
            self.priority = priority
        if state is not None:
            self.state = state
        if title is not None:
            self.title = title
        if version is not None:
            self.version = version

    @property
    def assignee(self):
        """Gets the assignee of this IssueChangeChanges.  # noqa: E501


        :return: The assignee of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._assignee

    @assignee.setter
    def assignee(self, assignee):
        """Sets the assignee of this IssueChangeChanges.


        :param assignee: The assignee of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._assignee = assignee

    @property
    def component(self):
        """Gets the component of this IssueChangeChanges.  # noqa: E501


        :return: The component of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this IssueChangeChanges.


        :param component: The component of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._component = component

    @property
    def content(self):
        """Gets the content of this IssueChangeChanges.  # noqa: E501


        :return: The content of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this IssueChangeChanges.


        :param content: The content of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._content = content

    @property
    def kind(self):
        """Gets the kind of this IssueChangeChanges.  # noqa: E501


        :return: The kind of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this IssueChangeChanges.


        :param kind: The kind of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._kind = kind

    @property
    def milestone(self):
        """Gets the milestone of this IssueChangeChanges.  # noqa: E501


        :return: The milestone of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._milestone

    @milestone.setter
    def milestone(self, milestone):
        """Sets the milestone of this IssueChangeChanges.


        :param milestone: The milestone of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._milestone = milestone

    @property
    def priority(self):
        """Gets the priority of this IssueChangeChanges.  # noqa: E501


        :return: The priority of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this IssueChangeChanges.


        :param priority: The priority of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._priority = priority

    @property
    def state(self):
        """Gets the state of this IssueChangeChanges.  # noqa: E501


        :return: The state of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this IssueChangeChanges.


        :param state: The state of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._state = state

    @property
    def title(self):
        """Gets the title of this IssueChangeChanges.  # noqa: E501


        :return: The title of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this IssueChangeChanges.


        :param title: The title of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._title = title

    @property
    def version(self):
        """Gets the version of this IssueChangeChanges.  # noqa: E501


        :return: The version of this IssueChangeChanges.  # noqa: E501
        :rtype: IssueChangeChangesAssignee
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this IssueChangeChanges.


        :param version: The version of this IssueChangeChanges.  # noqa: E501
        :type: IssueChangeChangesAssignee
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IssueChangeChanges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
