# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PipelineKnownHostAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hostname': 'str',
        'public_key': 'PipelineSshPublicKey',
        'uuid': 'str'
    }

    attribute_map = {
        'hostname': 'hostname',
        'public_key': 'public_key',
        'uuid': 'uuid'
    }

    def __init__(self, hostname=None, public_key=None, uuid=None):  # noqa: E501
        """PipelineKnownHostAllOf - a model defined in OpenAPI"""  # noqa: E501

        self._hostname = None
        self._public_key = None
        self._uuid = None
        self.discriminator = None

        if hostname is not None:
            self.hostname = hostname
        if public_key is not None:
            self.public_key = public_key
        if uuid is not None:
            self.uuid = uuid

    @property
    def hostname(self):
        """Gets the hostname of this PipelineKnownHostAllOf.  # noqa: E501

        The hostname of the known host.  # noqa: E501

        :return: The hostname of this PipelineKnownHostAllOf.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this PipelineKnownHostAllOf.

        The hostname of the known host.  # noqa: E501

        :param hostname: The hostname of this PipelineKnownHostAllOf.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def public_key(self):
        """Gets the public_key of this PipelineKnownHostAllOf.  # noqa: E501


        :return: The public_key of this PipelineKnownHostAllOf.  # noqa: E501
        :rtype: PipelineSshPublicKey
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this PipelineKnownHostAllOf.


        :param public_key: The public_key of this PipelineKnownHostAllOf.  # noqa: E501
        :type: PipelineSshPublicKey
        """

        self._public_key = public_key

    @property
    def uuid(self):
        """Gets the uuid of this PipelineKnownHostAllOf.  # noqa: E501

        The UUID identifying the known host.  # noqa: E501

        :return: The uuid of this PipelineKnownHostAllOf.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this PipelineKnownHostAllOf.

        The UUID identifying the known host.  # noqa: E501

        :param uuid: The uuid of this PipelineKnownHostAllOf.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineKnownHostAllOf):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
