# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PipelinesConfigAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'enabled': 'bool',
        'repository': 'Repository'
    }

    attribute_map = {
        'enabled': 'enabled',
        'repository': 'repository'
    }

    def __init__(self, enabled=None, repository=None):  # noqa: E501
        """PipelinesConfigAllOf - a model defined in OpenAPI"""  # noqa: E501

        self._enabled = None
        self._repository = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if repository is not None:
            self.repository = repository

    @property
    def enabled(self):
        """Gets the enabled of this PipelinesConfigAllOf.  # noqa: E501

        Whether Pipelines is enabled for the repository.  # noqa: E501

        :return: The enabled of this PipelinesConfigAllOf.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this PipelinesConfigAllOf.

        Whether Pipelines is enabled for the repository.  # noqa: E501

        :param enabled: The enabled of this PipelinesConfigAllOf.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def repository(self):
        """Gets the repository of this PipelinesConfigAllOf.  # noqa: E501


        :return: The repository of this PipelinesConfigAllOf.  # noqa: E501
        :rtype: Repository
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this PipelinesConfigAllOf.


        :param repository: The repository of this PipelinesConfigAllOf.  # noqa: E501
        :type: Repository
        """

        self._repository = repository

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelinesConfigAllOf):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
