# coding: utf-8

"""
    Bitbucket API

    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bitbucket.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SnippetCommitAllOfLinks(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'diff': 'AccountAllOfLinksAvatar',
        'html': 'AccountAllOfLinksAvatar',
        '_self': 'AccountAllOfLinksAvatar'
    }

    attribute_map = {
        'diff': 'diff',
        'html': 'html',
        '_self': 'self'
    }

    def __init__(self, diff=None, html=None, _self=None):  # noqa: E501
        """SnippetCommitAllOfLinks - a model defined in OpenAPI"""  # noqa: E501

        self._diff = None
        self._html = None
        self.__self = None
        self.discriminator = None

        if diff is not None:
            self.diff = diff
        if html is not None:
            self.html = html
        if _self is not None:
            self._self = _self

    @property
    def diff(self):
        """Gets the diff of this SnippetCommitAllOfLinks.  # noqa: E501


        :return: The diff of this SnippetCommitAllOfLinks.  # noqa: E501
        :rtype: AccountAllOfLinksAvatar
        """
        return self._diff

    @diff.setter
    def diff(self, diff):
        """Sets the diff of this SnippetCommitAllOfLinks.


        :param diff: The diff of this SnippetCommitAllOfLinks.  # noqa: E501
        :type: AccountAllOfLinksAvatar
        """

        self._diff = diff

    @property
    def html(self):
        """Gets the html of this SnippetCommitAllOfLinks.  # noqa: E501


        :return: The html of this SnippetCommitAllOfLinks.  # noqa: E501
        :rtype: AccountAllOfLinksAvatar
        """
        return self._html

    @html.setter
    def html(self, html):
        """Sets the html of this SnippetCommitAllOfLinks.


        :param html: The html of this SnippetCommitAllOfLinks.  # noqa: E501
        :type: AccountAllOfLinksAvatar
        """

        self._html = html

    @property
    def _self(self):
        """Gets the _self of this SnippetCommitAllOfLinks.  # noqa: E501


        :return: The _self of this SnippetCommitAllOfLinks.  # noqa: E501
        :rtype: AccountAllOfLinksAvatar
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this SnippetCommitAllOfLinks.


        :param _self: The _self of this SnippetCommitAllOfLinks.  # noqa: E501
        :type: AccountAllOfLinksAvatar
        """

        self.__self = _self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnippetCommitAllOfLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
